name: Cancel workflow if automated issue present
on: 
  issues:
    types:
      - labeled

jobs:
  cancel:
    name: Cancel workflow
    if: github.event.label.name == 'lychee'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          workflow_id: 15943138 # ./fetch-hosts.yaml