name: Check link if reachable
on:
  push:
    tags:
      - "release*"
      - "testing*"
  # Schedule for action to download latest files each 7 days
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  checkLink:
    name: Check link if reachable
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.1
        with:
          args: -v -c "config/lychee.toml" -n "config/links.txt" -b .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue, lychee